apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 3001        # Port exposed by the service
      targetPort: 3001   # Port on the container
  type: NodePort         # Expose via NodePort
