apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8082        # Port used by the service
      # targetPort: 8082  # Port on the container
      # nodePort: 30007 # NodePort (optional; Kubernetes assigns a port if omitted)
  # type: NodePort
