apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  labels:
    app: my-first-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
      - name: my-first-container
        image: nginx:latest
        ports:
        - containerPort: 80