apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.name }}
  name:  {{ .Values.service.name }}
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:  {{ .Values.deployment.name }}
  type: NodePort
